#!/bin/bash 

#for arch updates
os_file=/etc/os-release
 
if grep -q "arch" $os_file
then 
	sudo pacman -Syu
fi
#for ubuntu updates
if grep -q "Ubuntu" $os_file
then
	sudo apt-get update && sudo apt-get upgrade 
	sudo apt update 
	sudo apt install update 
	sudo apt full-upgrade
	sudo apt install upgrade 
	sudo apt autoremove
fi



